from datetime import datetime
from uuid import uuid4
from sqlalchemy import Column, String, Integer, Float, Text, DateTime, ForeignKey
from sqlalchemy.orm import relationship
from app.database import Base

class Segment(Base):
    """Audience segment generated by AI or defined manually."""
    __tablename__ = "segments"

    id = Column(String(36), primary_key=True, default=lambda: str(uuid4()))
    created_by = Column(String(36), ForeignKey("users.id"), nullable=True)
    name = Column(String(255), nullable=False)
    description = Column(Text, nullable=True)
    rules = Column(Text, nullable=False)  # JSON string representing the conditions/rules
    ai_reasoning = Column(Text, nullable=True)
    confidence_score = Column(Float, nullable=True)
    audience_size = Column(Integer, default=0)
    created_at = Column(DateTime, default=datetime.utcnow)

    # Relationships
    campaigns = relationship("Campaign", back_populates="segment", cascade="all, delete-orphan")
